name: versee
description: "VERSEE - Apresentador de mídia para igrejas"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  audioplayers: ^5.2.1
  provider: ^6.1.2
  flutter_riverpod: ^2.5.0
  file_picker: ^8.0.6
  path_provider: ^2.1.2
  path: ^1.9.0
  video_thumbnail: ^0.5.3
  flutter_image_compress: ^2.3.0
  image: ^4.1.7
  # Media playback dependencies
  video_player: ^2.8.6
  chewie: ^1.8.1
  audio_session: ^0.1.19
  # Firebase dependencies (versões estáveis para Android)
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0
  cloud_functions: ^4.6.0
  # Bible API dependencies
  http: ^1.2.1
  shared_preferences: ^2.2.3
  crypto: ^3.0.3
  xml: ^6.4.2
  # Permission handling
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.2
  # Platform-specific dependencies
  # web: ^0.5.1  # Web platform APIs - removed for Android compatibility
  # presentation_displays: ^1.0.0  # Physical displays (coming soon)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo_versee.png"
  min_sdk_android: 21 # Android 5.0
  web:
    generate: true
    image_path: "assets/images/logo_versee.png"
    background_color: "#000000"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/logo_versee.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo_versee.png"
