// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRsO5PFlQ0uXO5a0OWFKwnNqwb7zynfpo',
    appId: '1:54784920826:web:c240b54628943dd2364d43',
    messagingSenderId: '54784920826',
    projectId: 'egxse64845cgaarz90nllkn1o0c1aw',
    authDomain: 'egxse64845cgaarz90nllkn1o0c1aw.firebaseapp.com',
    databaseURL: 'https://egxse64845cgaarz90nllkn1o0c1aw-default-rtdb.firebaseio.com',
    storageBucket: 'egxse64845cgaarz90nllkn1o0c1aw.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRCrtNDZyAh1cxjlM4I5viYOQXUpRa3Jc',
    appId: '1:54784920826:android:b5414ae3032ea7ff364d43',
    messagingSenderId: '54784920826',
    projectId: 'egxse64845cgaarz90nllkn1o0c1aw',
    databaseURL: 'https://egxse64845cgaarz90nllkn1o0c1aw-default-rtdb.firebaseio.com',
    storageBucket: 'egxse64845cgaarz90nllkn1o0c1aw.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMN7pQ9rS6tU8vW2x3Y4z5A6b7C8d9E0f',
    appId: '1:54784920826:ios:1a2b3c4d5e6f7890364d43',
    messagingSenderId: '54784920826',
    projectId: 'egxse64845cgaarz90nllkn1o0c1aw',
    storageBucket: 'egxse64845cgaarz90nllkn1o0c1aw.firebasestorage.app',
    iosBundleId: 'com.versee.app',
  );
}